---
- hosts: all
  become: false
  remote_user: ec2-user
  tasks:
  - name: Install git
    yum:
      name: git
      state: latest

  - name: Get the code and run the shell script
    script: /home/ubuntu/node-project/update-node.sh
    register: console

  - debug: msg="{{ console.stdout }}"

  - debug: msg="{{ console.stderr }}" 
  
  