---
- hosts: all
  become: true
  remote_user: ubuntu
  become_user: ubuntu
  tasks:

  - name: Get the code and run the shell script
    ansible.builtin.shell: |
        cd /home/ubuntu/
        git clone https://github.com/ndlovun/node-project.git
        cd node-project/
        ./update-node.sh
  