---
- hosts: all
  become: true
  remote_user: ubuntu
  become_user: ubuntu
  tasks:

  - name: Get the code and run the shell script
    script: /home/ubuntu/node-project/update-node.sh
    remote_src: true
    register: console

  - debug: msg="{{ console.stdout }}"

  - debug: msg="{{ console.stderr }}" 
  