---
- hosts: all
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Move shell script to Node server
    ansible.builtin.copy:
      src: update-node.sh
      dest: /home/ubuntu/node-project

  - name: Run the shell script 
    ansible.builtin.shell: |
        cd /home/ubuntu/node-project
        ./update-node.sh
   
  