---
- hosts: all
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Git pull in folder ~/node-project
    ansible.builtin.shell: |
        cd ~/node-project
        git pull
        npm install
        npm run start
  