---
- hosts: all
  become: true
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: Install git
    yum:
      name: git
      state: latest

  - name: Run the shell script
    script: /home/ec2-user/node-project/update-node.sh
    register: console

  - debug: msg="{{ console.stdout }}"

  - debug: msg="{{ console.stderr }}" 
  
